# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import student_pb2 as student__pb2


class StudentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HelloWorld = channel.unary_unary(
                '/Student/HelloWorld',
                request_serializer=student__pb2.HelloRequest.SerializeToString,
                response_deserializer=student__pb2.HelloResponse.FromString,
                )
        self.Add = channel.unary_unary(
                '/Student/Add',
                request_serializer=student__pb2.StudentInfo.SerializeToString,
                response_deserializer=student__pb2.Result.FromString,
                )
        self.QueryByID = channel.unary_unary(
                '/Student/QueryByID',
                request_serializer=student__pb2.StudentID.SerializeToString,
                response_deserializer=student__pb2.StudentInfo.FromString,
                )
        self.QueryByName = channel.unary_unary(
                '/Student/QueryByName',
                request_serializer=student__pb2.StudentName.SerializeToString,
                response_deserializer=student__pb2.StudentInfo.FromString,
                )
        self.Delete = channel.unary_unary(
                '/Student/Delete',
                request_serializer=student__pb2.StudentID.SerializeToString,
                response_deserializer=student__pb2.Result.FromString,
                )


class StudentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HelloWorld(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HelloWorld': grpc.unary_unary_rpc_method_handler(
                    servicer.HelloWorld,
                    request_deserializer=student__pb2.HelloRequest.FromString,
                    response_serializer=student__pb2.HelloResponse.SerializeToString,
            ),
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=student__pb2.StudentInfo.FromString,
                    response_serializer=student__pb2.Result.SerializeToString,
            ),
            'QueryByID': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryByID,
                    request_deserializer=student__pb2.StudentID.FromString,
                    response_serializer=student__pb2.StudentInfo.SerializeToString,
            ),
            'QueryByName': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryByName,
                    request_deserializer=student__pb2.StudentName.FromString,
                    response_serializer=student__pb2.StudentInfo.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=student__pb2.StudentID.FromString,
                    response_serializer=student__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Student', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Student(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HelloWorld(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Student/HelloWorld',
            student__pb2.HelloRequest.SerializeToString,
            student__pb2.HelloResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Student/Add',
            student__pb2.StudentInfo.SerializeToString,
            student__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Student/QueryByID',
            student__pb2.StudentID.SerializeToString,
            student__pb2.StudentInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Student/QueryByName',
            student__pb2.StudentName.SerializeToString,
            student__pb2.StudentInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Student/Delete',
            student__pb2.StudentID.SerializeToString,
            student__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
